language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t dyada/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dyada/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-dcoker"
  env: "ReactDcoker-env-1"
  bucket_name: "elasticbeanstalk-us-east-1-729835138549"
  bucket_path: "react-dcoker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
